export const MANAGER_HELP = [
  "Manager commands:",
  "/owed open promises, overdue first",
  "/themes what people are raising, with each report, its status and its date. Open items only",
  "/themes all includes fixed, verified, duplicate and won't fix. /themes 2 and /themes all 2 page through",
  "/helpers contribution points",
  "/member @name | code | reply what I hold about one member, including manager notes",
  "/ack <itemId> | /fixed <itemId> | /verify <itemId> | /reopen <itemId> change an item's status",
  "/duplicate <itemId> | /wontfix <itemId> close an item without fixing it",
  "/promise <itemId or @member> <YYYY-MM-DD> <text> promise something to a member",
  "/done <promiseId> mark a promise kept",
  "/note <text> a manager-only note, stored on a separate Walrus account the member bot cannot read",
  "/notes read those notes back",
  "/ambassador @member | /unambassador @member grant or remove the ambassador tier",
  "/answers every answer the community has on record, whether it is confirmed, and whether it is still reused",
  "/confirm <answerId> allow an answer to be reused when the same question comes up",
  "/retire <answerId> stop an answer being reused, forever",
  "/report a weekly draft written from counted data, with the data shown under it",
  "/status memory, queue, budget and sequence",
  "",
  "An item id can be shortened as long as it still matches exactly one item.",
  "Plain questions are answered from a summary this code builds, never from the model's own memory.",
].join("\n");
